#include "balancecontrol.h"
#include "resourcecontrol.h"
#include "rotations.h"
#include <math.h>
#include <stdio.h> //test printing only

/********************
 * Balance the subtree *root.
 * Returns the root of the subtree generated by balancing *root. 
 ********************/
struct Node *balance(struct Node *root) {

  double bf = balancefactor(root);
  //printf("%s%d%s%0.f\n", "Balance Factor of node ", *(int *) root->data, " is ", bf);

  /* Tree is balanced. */
  if(bf == 0 || bf == 1 || bf == -1) {
    return root;
  }

  /* Tree is left-heavy. */
  else if(bf == 2) {
    double lbf = balancefactor(root->lchild);
    if(lbf == 1) {return llrotation(root);}
    else if(lbf == -1) {return lrrotation(root);}
  }

  /* Tree is right-heavy. */
  else if(bf == -2) {
    double rbf = balancefactor(root->rchild);
    if(rbf == 1) {return rlrotation(root);}
    else if(rbf == -1) {return rrrotation(root);}
  }

  fprintf(stderr, "%s\n", "Tree is impossibly imbalanced.");
  exit(1);
}

/********************
 * Get node balance factor.
 * Returns the balance factor of node *root, which is the height of its lchild
 * minus the height of its rchild.
 ********************/
double balancefactor(struct Node *root) {

  if(root == NULL) {return 0;}

  return height(root->lchild) - height(root->rchild);
}

/********************
 * Get node height.
 * Returns the height of *node, which is the fmax() + 1 of its child nodes.
 ********************/
double height(struct Node *node) {

  if(node == NULL) {
    return -1;
  }

  //printf("%s%d%s%0.f\n", "Height of node ", *(int *) node->data, " is ", fmax(height(node->lchild), height(node->rchild)) + 1);

  return fmax(height(node->lchild), height(node->rchild)) + 1;
}

