#ifndef NODEMANIPULATION_H
#define NODEMANIPULATION_H

#include "datastructures.h"

/********************
 * Balance the subtree *root.
 * Returns the root of the subtree generated by balancing *root. 
 ********************/
struct Node *balance(struct Node *root);

/********************
 * Get node balance factor.
 * Returns the balance factor of node *root, which is the height of its lchild
 * minus the height of its rchild.
 ********************/
double balancefactor(struct Node *root);

/********************
 * Get node height.
 * Returns the height of *node, which is the fmax() + 1 of its child nodes.
 ********************/
double height(struct Node *node);

#endif /* NODEMANIPULATION_H */
